version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run production build
          command: npm run prod

workflows:
  version: 2
  build:
    jobs:
      - build
