name: Generate dist

on:
  push:
    branches:
      - master
      - "develop*"
      - "hotfix/*"

jobs:
  generate-dist:
    runs-on: ubuntu-latest

    steps:

      - name: Prepare git
        shell: bash
        run: |
          git config --global user.name "github-action[bot]"
          git config --global user.email "github-action[bot]@users.noreply.github.com"

      - name: Check out the src branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Generate dist
        shell: bash
        run: |
          set -v
                    
          git config --global pull.rebase false
          git fetch --unshallow || true

          npm ci 
          npm run prod
          git add -f ./dist

          git status

          if ! git diff-index --quiet HEAD; then
            echo "Adding changes to git"
            git commit -am "[bot] generate dist ($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
            git push
          else
            echo "exiting"
            exit 0;
          fi

